export type Checkpoint = {
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
};

export type Lesson = {
  id: string;
  moduleId: string;
  title: string;
  bigQuestion: string;
  explanation: string;
  keyConcepts: string[];
  example: string;
  checkpoint: Checkpoint;
  commonMistakes: string[];
  summary: string[];
};

export type CourseModule = {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  description: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estimatedTime: string;
  learningOutcomes: string[];
  keyConcepts: string[];
  lessons: Lesson[];
  relatedLab?: string;
  quizId: string;
};

export const courseModules: CourseModule[] = [
  {
    id: "m1",
    number: 1,
    title: "Business as a System",
    subtitle: "Enterprise organization, feedback, and process flows",
    description: "Understand organizations as adaptive business systems before diving into technology. Learn how feedback loops and distinct data, material, and information flows align with management control.",
    difficulty: "Beginner",
    estimatedTime: "45 mins",
    learningOutcomes: [
      "Explain the concept of an enterprise as an adaptive system",
      "Describe the role of feedback mechanisms in management control",
      "Distinguish between material flows, data flows, and management control flows",
      "Explain how business events trigger data capture in operational systems"
    ],
    keyConcepts: ["Adaptive Systems", "Feedback Loops", "Operational Data vs. Information Flow"],
    quizId: "q1",
    lessons: [
      {
        id: "l1-1",
        moduleId: "m1",
        title: "Enterprise as an Adaptive System",
        bigQuestion: "Why is a business considered a 'system', and how does it survive change?",
        explanation: "A business system is an organized collection of people, processes, and resources that interact to convert inputs (capital, materials) into valuable outputs (products, services). It is highly adaptive because it continuously senses changes in its external environment (customer demand, pricing, technology) and self-adjusts. Feedback loops serve as the system's steering wheel, letting the system check if outputs meet expectations and make corrections at the input or process stage.",
        keyConcepts: [
          "Inputs and Outputs: Resources consumed versus products, services, and data produced.",
          "Adaptive Mechanism: The capacity to detect changes and self-regulate.",
          "Feedback Loop: Using output metrics to govern current processes."
        ],
        example: "An online store sees a sudden 30% drop in checkout completions. A feedback loop immediately flags this, leading managers to discover a payment gateway error and quickly switch to a backup system.",
        checkpoint: {
          question: "What primary mechanism allows a business system to regulate itself in response to external changes?",
          options: [
            "Passive auditing",
            "Continuous feedback loops and adaptive self-regulation",
            "Fixed operational boundaries",
            "Elimination of all material variables"
          ],
          correctAnswer: "Continuous feedback loops and adaptive self-regulation",
          explanation: "Feedback loops capture output metrics and route them back to the input/management layer, enabling dynamic self-regulation."
        },
        commonMistakes: [
          "Assuming systems are rigid. Real-world systems must be flexible to survive.",
          "Ignoring the feedback loop, leading to open-loop failure where the system runs blind."
        ],
        summary: [
          "A business is a complex, adaptive open system interacting with its environment.",
          "Feedback loops are critical for controlling processes and adapting to external changes.",
          "Inputs, processes, and outputs must be monitored continuously."
        ]
      },
      {
        id: "l1-2",
        moduleId: "m1",
        title: "Mapping Material, Data, and Information Flows",
        bigQuestion: "What is the difference between data and information flows within a business?",
        explanation: "A business is connected by distinct, concurrent flows. Material flows track physical goods and logistics (procurement, assembly, shipping). Data flows represent the discrete transactional logs generated by these physical actions (e.g., barcoding a box). Information flows represent these raw data logs compiled and structured into reports for managers, who then respond by sending Management Control flows (decisions and commands) back to optimize the material processes.",
        keyConcepts: [
          "Material Flow: Physical supply chain movement.",
          "Data Flow: Digital footprints of physical events.",
          "Information Flow: Synthesized data utilized for decision-making.",
          "Management Control Flow: Direction and commands going back down the pyramid."
        ],
        example: "A warehousing facility scans a barcode (Data scan). This triggers an automated inventory deduction (Data flow). A weekly report flags that stock is low (Information flow), prompting the procurement manager to order more (Management control flow).",
        checkpoint: {
          question: "Which flow represents a manager's decision or action returned to operational processes?",
          options: [
            "Material flow",
            "Raw data flow",
            "Management control flow",
            "Feedback input flow"
          ],
          correctAnswer: "Management control flow",
          explanation: "Management control flow is the downward flow representing decisions, plans, and instructions sent to regulate the business."
        },
        commonMistakes: [
          "Treating data and information as the same thing. Data is raw logs; information is structured and actionable.",
          "Underestimating physical material processes as disconnected from digital records."
        ],
        summary: [
          "Information systems bridge physical material actions and strategic control.",
          "Data scanning and records generate the operational raw data flow.",
          "Processed, aggregated data becomes the info flow that drives management decisions."
        ]
      }
    ],
    relatedLab: "etl"
  },
  {
    id: "m2",
    number: 2,
    title: "Business Information Systems",
    subtitle: "TPS, MIS, DSS, and Enterprise Resource Planning (ERP)",
    description: "Explore the different systems supporting operational, tactical, and strategic management. Learn the role of ERP in aligning finance, HR, sales, and manufacturing.",
    difficulty: "Beginner",
    estimatedTime: "50 mins",
    learningOutcomes: [
      "Distinguish between TPS, MIS, and DSS based on target users and decision types",
      "Explain the conceptual role and modules of Enterprise Resource Planning (ERP) systems",
      "Describe how communication and collaboration systems connect distinct organizational layers",
      "Connect functional departments with specific information system modules"
    ],
    keyConcepts: ["System Hierarchy (TPS/MIS/DSS)", "ERP Systems", "Functional Modules"],
    quizId: "q2",
    lessons: [
      {
        id: "l2-1",
        moduleId: "m2",
        title: "The Information System Pyramid",
        bigQuestion: "How do information needs differ across operational, tactical, and strategic layers?",
        explanation: "Information needs match the organizational hierarchy: \n1. Operational Layer: Needs high-volume, structured, transaction-specific detail provided by Transaction Processing Systems (TPS) (e.g., cash register records).\n2. Tactical Layer: Needs consolidated, summarized performance metrics provided by Management Information Systems (MIS) to compare plans with results (e.g., monthly sales reports).\n3. Strategic Layer: Needs broad, long-term, predictive, and multi-variable support provided by Decision Support Systems (DSS) to evaluate unstructured scenarios (e.g., launching a new product line).",
        keyConcepts: [
          "TPS (Transaction Processing System): High-speed transaction recording for operational workers.",
          "MIS (Management Information System): Summarized, routine reports for tactical managers.",
          "DSS (Decision Support System): Analytical tools and models for strategic planners."
        ],
        example: "A retail bank uses a TPS to record daily deposits, an MIS to show branch performance over the quarter, and a DSS to model the financial impact of changing home loan interest rates.",
        checkpoint: {
          question: "A strategic planner wants to model hypothetical market entry scenarios. Which system is most appropriate?",
          options: [
            "A transactional scanner (TPS)",
            "A routine monthly report generator (MIS)",
            "An analytical Decision Support System (DSS)",
            "A local document management tool"
          ],
          correctAnswer: "An analytical Decision Support System (DSS)",
          explanation: "DSS systems combine data with mathematical modeling to support complex, semi-structured, and unstructured strategic decisions."
        },
        commonMistakes: [
          "Using raw transactional logs (TPS) directly for strategic summaries without cleaning and aggregation.",
          "Expecting DSS tools to record daily sales. Different tools serve different levels."
        ],
        summary: [
          "TPS handles high-volume operational transactions.",
          "MIS summarizes history to monitor tactical goals.",
          "DSS models complex future scenarios under uncertainty for strategic leadership."
        ]
      },
      {
        id: "l2-2",
        moduleId: "m2",
        title: "Enterprise Resource Planning (ERP)",
        bigQuestion: "How does an ERP system eliminate isolated information silos?",
        explanation: "In traditional companies, departments (Finance, Sales, Production, HR) used isolated databases, creating conflicting records. Enterprise Resource Planning (ERP) systems solve this by sharing a single database and a unified user interface. When sales updates a customer order, the finance module immediately records the revenue, manufacturing schedules the build, and warehouse inventory adjustments trigger a replenishment order—all instantly, securely, and automatically.",
        keyConcepts: [
          "Silos: Isolated systems that hinder cross-department collaboration.",
          "Unified Database: The core of ERP that ensures consistent, real-time records across the business.",
          "Functional Modules: Specialized app sections (Finance, HR, Logistics) sharing a single dataset."
        ],
        example: "In an ERP, scanning a raw material barcode immediately records the inventory change, schedules production, and updates procurement forecasts without manual data entry.",
        checkpoint: {
          question: "What is the primary benefit of an integrated ERP system over traditional isolated software?",
          options: [
            "Lower raw CPU utilization",
            "Elimination of silos through a common, real-time shared database",
            "Manual file synchronization support",
            "Isolated local spreadsheets"
          ],
          correctAnswer: "Elimination of silos through a common, real-time shared database",
          explanation: "ERP integrates functional modules around a single, real-time shared database, eliminating isolated data silos."
        },
        commonMistakes: [
          "Viewing ERP as a single app. It is a comprehensive suite of modules built on a shared database.",
          "Assuming ERP automatically improves business processes. Implementation requires process redesign."
        ],
        summary: [
          "ERP integrates all functional business domains under one digital roof.",
          "Shared databases ensure high data consistency and real-time operations.",
          "Modern ERP (ERP II) extends integration to suppliers and customers."
        ]
      }
    ],
    relatedLab: "olap"
  },
  {
    id: "m3",
    number: 3,
    title: "Business Analysis, Analytics & BI",
    subtitle: "Defining and distinguishing roles, intelligence scopes, and data science",
    description: "Clarify the differences between Business Analysis, Business Analytics, and Business Intelligence. Understand client, competitive, and process intelligence, then connect those ideas to analytics maturity and big data technologies.",
    difficulty: "Intermediate",
    estimatedTime: "80 mins",
    learningOutcomes: [
      "Distinguish Business Analysis from Business Analytics and Business Intelligence",
      "Describe the five categories of corporate business intelligence",
      "Understand how BI differs from deep Data Science and predictive methods",
      "List typical deliverables for analysts, BI developers, and data scientists",
      "Distinguish between descriptive, diagnostic, predictive, and prescriptive analytics",
      "Explain the fundamental logic of NoSQL databases and the MapReduce programming framework"
    ],
    keyConcepts: ["Analysis vs. Analytics", "BI Subsets", "BI vs. Data Science", "Analytics Maturity Spectrum", "Big Data"],
    quizId: "q3",
    lessons: [
      {
        id: "l3-1",
        moduleId: "m3",
        title: "Analysis vs. Analytics vs. BI",
        bigQuestion: "What are the distinct focuses of business analysis, business analytics, and business intelligence?",
        explanation: "Although they sound similar, these terms refer to different disciplines:\n- **Business Analysis**: Focuses on organizational structures, processes, and systems to define business needs and recommend changes (solutions).\n- **Business Analytics**: Focuses on quantitative, statistical modeling of historic data to predict patterns and optimize decisions.\n- **Business Intelligence (BI)**: Focuses on historical monitoring, reporting, and building user dashboards to show how the business is running right now.",
        keyConcepts: [
          "Business Analysis: Focused on change, requirements, and process improvement.",
          "Business Analytics: Focused on statistics, math, and predictive modeling.",
          "Business Intelligence: Focused on dashboards, routine reports, and corporate performance tracking."
        ],
        example: "A company struggling with inventory issues hires a **Business Analyst** to map warehouse bottlenecks, uses **Business Intelligence** dashboards to track real-time stock levels, and applies **Business Analytics** models to forecast next month's product demand.",
        checkpoint: {
          question: "Which discipline focuses on defining business needs and recommending process changes?",
          options: [
            "Business Analytics",
            "Business Analysis",
            "Business Intelligence",
            "Statistical Forecasting"
          ],
          correctAnswer: "Business Analysis",
          explanation: "Business Analysis is defined as the practice of enabling change by defining needs and recommending solutions that deliver value."
        },
        commonMistakes: [
          "Assuming BI is predictive. BI is generally retrospective (what happened), while advanced analytics is prospective (what will happen).",
          "Hiring a data scientist to map a business workflow, which is typically a business analyst's job."
        ],
        summary: [
          "Business Analysis maps processes, requirements, and business rules.",
          "Business Intelligence delivers real-time monitoring and reporting.",
          "Business Analytics uses statistics and mathematics to identify patterns and predict future states."
        ]
      },
      {
        id: "l3-2",
        moduleId: "m3",
        title: "The Analytics Maturity Spectrum",
        bigQuestion: "How do we move from understanding history to automating decisions?",
        explanation: "As organizations develop their analytical capabilities, they progress along an analytics maturity spectrum. This journey increases both the **business value** and the **technical difficulty** of their analytics:\n1. **Descriptive Analytics**: Focuses on 'What happened?' using reporting, SQL queries, and dashboards.\n2. **Diagnostic Analytics**: Focuses on 'Why did it happen?' using data drilling and correlation analysis.\n3. **Predictive Analytics**: Focuses on 'What will happen?' using machine learning, regression, and forecasting models.\n4. **Prescriptive Analytics**: Focuses on 'How can we make it happen?' using optimization algorithms, decision rules, and simulation models to recommend or automate actions.",
        keyConcepts: [
          "Descriptive: Explains past outcomes using historical reports and dashboards.",
          "Diagnostic: Finds root causes by drilling into anomalies in historic data.",
          "Predictive: Forecasts future outcomes using statistical modeling.",
          "Prescriptive: Suggests optimized actions or automates decisions using algorithms."
        ],
        example: "A ride-sharing app uses descriptive analytics to report yesterday's trip count, diagnostic analytics to understand why rides dropped in a specific neighborhood (e.g., bad weather), predictive analytics to forecast demand for the upcoming hour, and prescriptive analytics to dynamically adjust surge pricing and match drivers.",
        checkpoint: {
          question: "Which type of analytics focuses on recommending optimized courses of action?",
          options: [
            "Descriptive analytics",
            "Diagnostic analytics",
            "Predictive analytics",
            "Prescriptive analytics"
          ],
          correctAnswer: "Prescriptive analytics",
          explanation: "Prescriptive analytics combines predictions with decision rules to recommend or automate optimized business actions."
        },
        commonMistakes: [
          "Expecting descriptive dashboards to automatically predict future sales without statistical forecasting.",
          "Jumping to prescriptive automation before building a solid foundation of descriptive data."
        ],
        summary: [
          "Descriptive analytics reports the past; diagnostic explains the causes.",
          "Predictive analytics forecasts the future; prescriptive recommends the optimal action.",
          "Higher analytical maturity delivers greater business value but requires more sophisticated mathematical models."
        ]
      }
    ],
    relatedLab: "olap"
  },
  {
    id: "m4",
    number: 4,
    title: "Data Warehousing and ETL",
    subtitle: "Analytical repositories, subject orientation, and ETL pipelines",
    description: "Learn how data is extracted, transformed, and loaded into analytical warehouses. Understand consolidation, data quality, and operational vs. analytical differences.",
    difficulty: "Intermediate",
    estimatedTime: "50 mins",
    learningOutcomes: [
      "Explain the core characteristics of a data warehouse (subject-oriented, integrated, non-volatile, time-variant)",
      "Map the step-by-step ETL (Extraction, Transformation, Load) pipeline",
      "Describe typical data transformation tasks (cleaning, consolidation, normalization, reduction)",
      "Distinguish operational transactional databases (OLTP) from analytical repositories (OLAP)"
    ],
    keyConcepts: ["Data Warehouse Core Features", "ETL Process Stages", "Data Cleaning & Integration"],
    quizId: "q4",
    lessons: [
      {
        id: "l4-1",
        moduleId: "m4",
        title: "The Data Warehouse Concept",
        bigQuestion: "Why do we need a separate repository instead of querying production systems?",
        explanation: "Operational transactional databases (OLTP) are optimized to write individual rows quickly to run daily business processes (e.g., recording a purchase). Running large analytical queries on these systems can slow down or crash them. A **Data Warehouse (DWH)** is a separate repository optimized specifically for querying millions of rows. It has four key characteristics:\n1. **Subject-Oriented**: Organized around business concepts (e.g., Sales, Customers) rather than system actions.\n2. **Integrated**: Standardizes inconsistent data from multiple departments into one unified format.\n3. **Non-Volatile**: Data is read-only once loaded, ensuring historical consistency.\n4. **Time-Variant**: Stores historical snapshots over years to track trends.",
        keyConcepts: [
          "OLTP (Online Transaction Processing): Operational databases optimized for frequent writes.",
          "DWH (Data Warehouse): Read-only analytical databases optimized for complex, multi-row reads.",
          "Integrated Data: Consolidated data formats (e.g., standardizing custom gender tags like M/F/1/0 to a single standard)."
        ],
        example: "A multinational retailer processes 50 purchases per second on its transactional database. At midnight, these transactions are extracted, cleaned, and loaded into the DWH so business analysts can run quarterly performance queries without slowing down the active registers.",
        checkpoint: {
          question: "Which of the following describes a key characteristic of data warehouses?",
          options: [
            "Highly volatile with constant user modifications",
            "Subject-oriented, integrated, non-volatile, and time-variant historical records",
            "Optimized for high-speed row-by-row operational writes",
            "Unstructured local text files"
          ],
          correctAnswer: "Subject-oriented, integrated, non-volatile, and time-variant historical records",
          explanation: "Inmon's classic definition outlines DWH as subject-oriented, integrated, non-volatile, and time-variant."
        },
        commonMistakes: [
          "Directly querying the active transactional database for heavy reports, slowing down business operations.",
          "Loading dirty, inconsistent data into a DWH without standardizing it first, causing incorrect reporting results."
        ],
        summary: [
          "Operational databases handle real-time transactions; DWH supports reporting and analytics.",
          "DWH integrates diverse company-wide data into a single repository.",
          "Data in a DWH is historical, read-only (non-volatile), and organized by subject."
        ]
      },
      {
        id: "l4-2",
        moduleId: "m4",
        title: "The ETL Pipeline",
        bigQuestion: "How does data safely travel from raw operational systems into the DWH?",
        explanation: "Data integration relies on **ETL (Extract, Transform, Load)** procedures. ETL typically takes up about 60% of a data warehousing project's time and effort:\n- **Extraction**: Connecting to various databases (sales, HR, external marketing) and reading new transactional records.\n- **Transformation**: The most complex stage. Data is consolidated, duplicates are removed, currencies are converted to a standard, missing values are handled, and keys are aligned.\n- **Loading**: Writing the clean, structured data into the target warehouse tables, typically as part of a scheduled nightly batch job.",
        keyConcepts: [
          "Extraction: Connecting to diverse systems to pull fresh raw transactional records.",
          "Transformation: Data cleaning, formatting, and applying business logic.",
          "Loading: Appending or writing clean rows into the warehouse schema."
        ],
        example: "An ETL job pulls purchase logs from a US server (USD) and an EU server (EUR), removes duplicate entries, converts USD values to EUR using the daily exchange rate, and appends the unified sales records to the central data warehouse.",
        checkpoint: {
          question: "During which ETL stage is currency standardization or duplicate removal performed?",
          options: [
            "Extraction",
            "Transformation",
            "Loading",
            "Backup mirroring"
          ],
          correctAnswer: "Transformation",
          explanation: "Transformation includes all tasks relating to cleaning, formatting, standardizing, and checking data quality."
        },
        commonMistakes: [
          "Skipping the transformation phase, which loads corrupt, messy data into the warehouse.",
          "Running ETL updates during peak daytime business hours, slowing down both transactional systems and the DWH."
        ],
        summary: [
          "ETL is the data transport system that populates the DWH.",
          "Transformation handles data cleaning, duplicate removal, and standardization.",
          "Scheduled loading runs during off-peak hours to maintain DWH consistency."
        ]
      }
    ],
    relatedLab: "etl"
  },
  {
    id: "m5",
    number: 5,
    title: "OLAP, Dashboards & Dimensional Analytics",
    subtitle: "Data cubes, dimensions, slice & dice, and KPI alerting",
    description: "Discover the core operations of multidimensional data cubes: slice, dice, pivot, drill-down, and drill-up. Understand performance dashboards and early warning alerts.",
    difficulty: "Intermediate",
    estimatedTime: "45 mins",
    learningOutcomes: [
      "Perform multidimensional operations: slice, dice, pivot, drill-down, and drill-up",
      "Model datasets into dimensions (attributes) and measures (facts)",
      "Build visual dashboard mockups with appropriate KPI choices",
      "Configure thresholds for automated early warning and alert systems"
    ],
    keyConcepts: ["OLAP Operations", "KPI Dashboards", "Early Warning Alerts"],
    quizId: "q5",
    lessons: [
      {
        id: "l5-1",
        moduleId: "m5",
        title: "Multidimensional Data & OLAP Cubes",
        bigQuestion: "How do data cubes enable instant multi-angle business queries?",
        explanation: "Traditional spreadsheets represent data in flat two-dimensional grids. **OLAP (Online Analytical Processing)** structures data into multidimensional **Data Cubes**. This format separates business facts into:\n- **Measures**: Numerical values you want to analyze (e.g., Sales revenue, Units sold).\n- **Dimensions**: Business categories you analyze by (e.g., Region, Product type, Time period).\nUsing OLAP, managers can instantly interact with data using five main operations:\n1. **Slice**: Filter the cube by a single dimension (e.g., viewing only Q1).\n2. **Dice**: Filter by a subset of multiple dimensions (e.g., Q1/Q2 and Laptops/Tablets in the Istria region).\n3. **Pivot**: Rotate the view to swap columns and rows.\n4. **Drill-down**: Navigate from summary details to granular details (e.g., Year $\\to$ Month $\\to$ Day).\n5. **Drill-up**: Aggregate details back to a high-level summary (e.g., Store $\\to$ City $\\to$ Country).",
        keyConcepts: [
          "Measures: Numerical values (facts) like sales volume, profit, or expenses.",
          "Dimensions: Analytical filters like Time, Geography, or Product Categories.",
          "OLAP Operations: Slicing, dicing, pivoting, drilling down, and drilling up."
        ],
        example: "A regional manager pivots a sales cube to compare monthly performance across product lines, then drills down on an underperforming category to see which specific products are causing the drop.",
        checkpoint: {
          question: "Which OLAP operation changes the view from quarterly summarized sales to daily transaction details?",
          options: [
            "Drill-up",
            "Drill-down",
            "Pivot",
            "Slice"
          ],
          correctAnswer: "Drill-down",
          explanation: "Drilling down expands summarized levels to show more granular details (from years to months to days)."
        },
        commonMistakes: [
          "Confusing dimensions (categorical filters) with measures (numerical facts).",
          "Attempting to slice a dataset without setting a specific dimension category first."
        ],
        summary: [
          "Data Cubes organize business data into multi-dimensional dimensions and measures.",
          "OLAP operations let users pivot, slice, and dice data cubes dynamically.",
          "Drill-down reveals detail; drill-up summarizes metrics for strategic overviews."
        ]
      }
    ],
    relatedLab: "olap"
  },
  {
    id: "m7",
    number: 7,
    title: "Decision Analysis",
    subtitle: "Formal problem structures, criteria, risk, and uncertainty",
    description: "Learn how to structure complex business decisions. Define problem statements, alternatives, and evaluation criteria under conditions of risk and uncertainty.",
    difficulty: "Advanced",
    estimatedTime: "40 mins",
    learningOutcomes: [
      "Formulate clear, structured problem statements for business decisions",
      "Identify distinct, mutually exclusive alternatives and evaluation criteria",
      "Understand several techniques for making decisions under risk and uncertainty",
      "Evaluate alternatives systematically using quantitative models"
    ],
    keyConcepts: ["Problem Definition", "Alternatives and Criteria", "Decisions Under Uncertainty"],
    quizId: "q7",
    lessons: [
      {
        id: "l7-1",
        moduleId: "m7",
        title: "Structuring Decision Problems",
        bigQuestion: "How do we define a complex decision problem systematically?",
        explanation: "Decision analysis is a systematic approach to assessing complex problems and potential choices to find the best outcome under uncertainty. It divides a decision problem into five clear steps:\n1. **Define the Problem Statement**: Clearly describe the decision to be made.\n2. **Identify Alternatives**: Brainstorm the different choices available.\n3. **Establish Criteria**: Agree on the metrics used to evaluate the choices (e.g., cost, risk, quality).\n4. **Evaluate Alternatives**: Analyze how each choice performs against the criteria.\n5. **Select and Implement**: Choose the highest-scoring choice and execute it.",
        keyConcepts: [
          "Alternatives: The different choices available to the decision-maker.",
          "Criteria: The standards or measures used to evaluate and compare alternatives.",
          "Uncertainty: External factors out of the decision-maker's control that affect outcomes."
        ],
        example: "A logistics company decides to upgrade its delivery fleet. The problem is fleet replacement, the alternatives are electric vans, hybrid vans, or traditional diesel vans, and the criteria are purchase cost, fuel efficiency, emission targets, and maintenance reliability.",
        checkpoint: {
          question: "What is the first step in structuring a decision analysis problem systematically?",
          options: [
            "Calculate expected values",
            "Define the problem statement clearly",
            "Establish pairwise comparisons",
            "Select the cheapest option immediately"
          ],
          correctAnswer: "Define the problem statement clearly",
          explanation: "Systematic decision analysis always starts by defining the problem statement clearly."
        },
        commonMistakes: [
          "Listing biased alternatives designed to make one choice look artificially superior.",
          "Failing to agree on evaluation criteria before analyzing alternatives, leading to stakeholder disagreement."
        ],
        summary: [
          "Decision analysis breaks complex, risky decisions into clear, manageable steps.",
          "Alternatives represent the choices; criteria represent the standards for evaluation.",
          "Structuring the problem reduces bias and creates consensus among stakeholders."
        ]
      }
    ],
    relatedLab: "decision-tree"
  },
  {
    id: "m8",
    number: 8,
    title: "Decision Modelling",
    subtitle: "Repeatable business decisions, rules, tables, and trees",
    description: "Learn to model repeatable operational business decisions. Build decision tables, read decision trees, and understand Decision Requirements Diagrams (DRDs).",
    difficulty: "Advanced",
    estimatedTime: "50 mins",
    learningOutcomes: [
      "Identify repeatable, operational business decisions suitable for rules automation",
      "Construct well-formed decision tables that are clear, complete, and consistent",
      "Read and build decision trees to represent sequential choices",
      "Explain the key elements of a Decision Requirements Diagram (DRD)"
    ],
    keyConcepts: ["Repeatable Decisions", "Decision Tables and Trees", "Decision Requirements Diagrams"],
    quizId: "q8",
    lessons: [
      {
        id: "l8-1",
        moduleId: "m8",
        title: "Decision Tables and Rules",
        bigQuestion: "How can we structure complex operational rules into a transparent table?",
        explanation: "Many business decisions are operational and repeatable (e.g., approving an order or calculating a tax rate). Instead of relying on manual work or complex code, we can structure these decisions into **Decision Tables**. A decision table is a compact, clean representation of business logic. It consists of:\n- **Conditions**: The inputs evaluated by the rules (columns on the left).\n- **Outcomes (Actions)**: The result when conditions are met (columns on the right).\n- **Rules**: Rows that map specific condition values to outcomes.\nTo ensure accuracy, decision tables must be regularly checked for:\n1. **Completeness**: Are there rules covering every possible combination of inputs?\n2. **Consistency (Overlaps)**: Are there overlapping rules that could output conflicting actions for the same inputs?",
        keyConcepts: [
          "Definitional Rules: Logic based on strict definitions (e.g., calculating tax).",
          "Behavioral Rules: Rules that guide or check actions (e.g., flagging high risk).",
          "Overlapping Rules: A logical error where multiple rows in a decision table match the same inputs but output different results."
        ],
        example: "An online retailer uses a decision table to instantly evaluate incoming orders: if customer is 'Premium' and risk score is 'Low' and payment is 'Verified' $\\to$ 'Approve' the order automatically. If risk score is 'High' $\\to$ 'Reject' immediately.",
        checkpoint: {
          question: "What is the primary risk of having overlapping rules in a decision table?",
          options: [
            "Increased database storage size",
            "Logical conflict where multiple rules match the same inputs but yield different decisions",
            "Slow calculation speeds",
            "Lack of clean visual mapping"
          ],
          correctAnswer: "Logical conflict where multiple rules match the same inputs but yield different decisions",
          explanation: "Overlapping rules create logical conflicts where the system cannot determine which action to take for a given set of inputs."
        },
        commonMistakes: [
          "Creating decision tables with missing combinations, leaving some transactions with no decision (incompleteness).",
          "Mixing unrelated inputs in the same table, making the decision logic unnecessarily complex."
        ],
        summary: [
          "Decision tables map input conditions to clear, consistent operational outcomes.",
          "They support rule-based automation, increasing speed and reducing errors.",
          "High-quality tables must be complete (no missing cases) and consistent (no conflicting rules)."
        ]
      }
    ],
    relatedLab: "decision-table"
  },
  {
    id: "m9",
    number: 9,
    title: "AHP Decision Lab",
    subtitle: "Analytic Hierarchy Process theory and multi-criteria comparison",
    description: "Understand the mathematical and psychological foundations of the Analytic Hierarchy Process (AHP). Learn Saaty's scale and consistency check principles.",
    difficulty: "Advanced",
    estimatedTime: "40 mins",
    learningOutcomes: [
      "Explain the conceptual steps of the Analytic Hierarchy Process",
      "Describe Saaty's 1-9 pairwise comparison scale and its verbal meanings",
      "Understand the calculation of local and global weights in AHP hierarchies",
      "Explain Consistency Index (CI) and Consistency Ratio (CR) thresholds"
    ],
    keyConcepts: ["AHP Hierarchy Structure", "Saaty Scale Pairwise Comparison", "Consistency Indexes (CI, CR)"],
    quizId: "q9",
    lessons: [
      {
        id: "l9-1",
        moduleId: "m9",
        title: "AHP Theory & Multi-Criteria Decisions",
        bigQuestion: "Why is AHP considered both a mathematical and psychological decision method?",
        explanation: "The **Analytic Hierarchy Process (AHP)**, developed by Thomas Saaty in the 1970s, is a multi-criteria decision-making method that combines math and psychology. It helps groups resolve complex choices by breaking them down into a three-level hierarchy:\n1. **Goal**: The final choice to be made (e.g., choosing a cloud provider).\n2. **Criteria**: The factors affecting the choice (e.g., price, availability, performance).\n3. **Alternatives**: The actual options to select from (e.g., Amazon, Azure, Google).\nInstead of asking judges to assign raw weights, AHP uses **Pairwise Comparisons**. Decision-makers compare options two at a time using Saaty's 1–9 scale, expressing their preferences verbally (e.g., 'Establishment is moderately more important than Availability zones'). The system then calculates weights and checks for consistency, ensuring logical decision-making.",
        keyConcepts: [
          "Goal, Criteria, and Alternatives: The standard three-level AHP hierarchy.",
          "Pairwise Comparison: Comparing two options at a time to reduce bias.",
          "Saaty Scale: A scale from 1 (equal importance) to 9 (extreme importance) used in comparisons."
        ],
        example: "A company choosing a new software vendor uses AHP. The directors compare cost vs. security, security vs. ease-of-use, and ease-of-use vs. cost in pairs, letting the AHP model calculate logical weights and select the optimal vendor.",
        checkpoint: {
          question: "According to Saaty's AHP scale, what does an intensity score of 1 represent?",
          options: [
            "Extreme preference",
            "Moderate preference",
            "Equal importance / contribution to the goal",
            "A logical conflict error"
          ],
          correctAnswer: "Equal importance / contribution to the goal",
          explanation: "In AHP, a score of 1 represents equal importance, where both elements contribute equally to the goal."
        },
        commonMistakes: [
          "Making completely contradictory comparisons (e.g., A > B, B > C, and C > A), resulting in an inconsistent model.",
          "Failing to structure a clear hierarchy before running pairwise comparisons."
        ],
        summary: [
          "AHP combines math and psychology to structure complex multi-criteria decisions.",
          "Pairwise comparisons simplify judgments and reduce bias.",
          "Calculating the consistency ratio (CR) ensures comparisons are logically sound."
        ]
      }
    ],
    relatedLab: "decision-table"
  }
];
